likes(deep,ai).
likes(deep,ml).
likes(henil,java).
likes(jatin,stock_market).
likes(krishn,reel).
likes(krishn,ai).
hobby(henil,coding).
hobby(deep,reading).
hobby(jatin,reading).
hobby(krishn,reading).
